---
- name: Install Remote Engine
  hosts: all
  
  vars:
    ansible_user: azureuser
    ansible_password: Temporary123
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
    jdk_package: openjdk11
    java_major_version: 11.0.16
    java_minor_version: 8
  
  tasks:

  
  - name: Download the file
    azure.azcollection.azure_rm_storageblob:
      resource_group: ansible-test
      storage_account_name: ansibletest12345678
      container: ansible-test
      blob: Talend-RemoteEngine-V2.11.7-229.zip
      dest: /home/azureuser/


  - name: Unzip a Talend Remote Engine file
    community.windows.win_unzip:
      src: C:\Users\azureuser\Talend-Remote-Engine-V"{{ tre_version }}"-229.zip
      dest: C:\Users\azureuser\Talend-Remote-V"{{ tre_version }}"-last

  - name: Run basic PowerShell script
    ansible.windows.win_powershell:
      script: |
        cd C:\Users\azureuser\Talend-RemoteEngine-V2.11.7\bin
        echo "feature:install wrapper `nwrapper:install -n talend-remote-engine `nlogout" | .\trun.bat
        .\talend-remote-engine-service.bat install
        net start 'talend-remote-engine'
