---
- name: Install Remote Engine
  hosts: all
  
  vars:
    ansible_user: azureuser
    ansible_password: Temporary123
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
    jdk_package: openjdk11
    java_major_version: 11.0.16
    java_minor_version: 8
  
  tasks:

  - name: Install Java
    win_chocolatey:
      name: "{{ jdk_package }}"
      state: present
      version: "{{ java_major_version }}"

  - name: Set Java_home
    win_environment:
      state: present
      name: JAVA_HOME
      value: 'c:\Program Files\OpenJDK\openjdk-{{ java_major_version }}_{{ java_minor_version }}'
      level: machine

  - name: Add Java to path
    win_path:
      elements:
        - 'c:\program files\java\OpenJDK\openjdk-{{ java_major_version }}_{{ java_minor_version }}\bin'

  - name: Copy Talend Remote Engine file
    win_copy:
      src: '/root/Talend-RemoteEngine-V{{ tre_version }}.zip'
      dest: C:\Users\azureuser
  
  - name: Unzip a Talend Remote Engine file
    community.windows.win_unzip:
      src: 'C:\Users\azureuser\Talend-RemoteEngine-V{{ tre_version }}.zip'
      dest: C:\Users\azureuser\
  
  - name: Copy Talend Remote Engine file
    win_copy:
      src: /root/preauthorized.key.cfg
      dest: 'C:\Users\azureuser\Talend-RemoteEngine-V{{ tre_version }}/etc/preauthorized.key.cfg'
        
  - name: Install Remote Talend Engine
    ansible.windows.win_powershell:
      script: |
        echo "pairing.service.url=https://pair.eu.cloud.talend.com" > 'Talend-RemoteEngine-V{{ tre_version }}/etc/org.talend.ipaas.rt.pairing.client.cfg'
        cd C:\Users\azureuser\Talend-RemoteEngine-V"{{ tre_version }}"\bin
        echo "feature:install wrapper `nwrapper:install -n talend-remote-engine `nlogout" | .\trun.bat
        .\talend-remote-engine-service.bat install
    register: result 
    until: result is not failed
    delay: 10 
    retries: 5 
  - name: Set service startup mode to auto and ensure it is started
    ansible.windows.win_service:
      name: 'talend-remote-engine'
      start_mode: auto
      state: started


