- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  
  - include_vars: /root/vars/ubuntu_vars.yml

  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{resource_group}}"
      location: "{{ vm_location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{vm_resource_group}}"
      name: "{{ virtual_network }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{vm_resource_group}}"
      name: "{{ virtual_subnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ virtual_network }}"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{vm_resource_group}}"
      #allocation_method: Static
      name: "{{ vm_public_ip }}"
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH and Tallend Cloud
    azure_rm_securitygroup:
      resource_group: "{{vm_resource_group}}"
      name: "{{ vm_security_group }}"
      rules: "{{ item }}"
    with_items: "{{ security_group_rules }}"
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{vm_resource_group}}"
      name: "{{ vm_network_interface }}"
      virtual_network: "{{ virtual_network }}"
      subnet: "{{ virtual_subnet }}"
      public_ip_name: "{{ vm_public_ip }}"
      security_group: "{{ vm_security_group }}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{vm_resource_group}}"
      name: "{{ vm_name }}"
      vm_size: "{{ vm_size }}"
      admin_username: "{{ vm_username }}"
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ lookup('file', '/root/id_rsa.pub') }}"
      network_interfaces: "{{ vm_network_interface }}"
      image:
        offer: "{{ os_offer }}"
        publisher: "{{ os_publisher }}"
        sku: "{{ vm_sku }}"
        version: "{{ os_version }}"