 - name: Install Remote Engine Playbook
   gather_facts: true
   hosts: all
   become: true
   tasks:
    
    - name: Install OpenJDK11
      become: yes
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache : true 
    
    - name: Install unzip 
      ansible.builtin.apt:
        name: unzip
        state: present 
    
    - name: Download Talend Remote Engine 
      become: yes
      ansible.builtin.copy:
        src: '/root/Talend-RemoteEngine-V{{ tre_version }}.zip'
        dest: /home/azureuser/
    
    - name: Extract Talend Remote Engine file
      ansible.builtin.unarchive:
        src: '/home/azureuser/Talend-RemoteEngine-V{{ tre_version }}.zip'
        dest: /home/azureuser/
        remote_src: true 
    
    - name: customize /etc/environment
      become: true 
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        line: "JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64"

    - name: Prepare environment
      become: true
      ansible.builtin.shell: |
        export PAIRING_KEY=$(cat preAuthoKey.txt)
        echo "remote.engine.pre.authorized.key = $PAIRING_KEY" > Talend-RemoteEngine-V2.11.7/etc/preauthorized.key.cfg
        echo "pairing.service.url=https://pair.eu.cloud.talend.com" > Talend-RemoteEngine-V2.11.7/etc/org.talend.ipaas.rt.pairing.client.cfg
    
    - name: Install Remote Engine
      become: true
      ansible.builtin.shell: |
        cd /home/azureuser/Talend-RemoteEngine-V2.11.7/bin
        echo "feature:install wrapper \n wrapper:install -n talend-remote-engine \n logout" | sh trun
      environment: 
        JAVA_HOME: /usr/lib/jvm/java-1.11.0-openjdk-amd64
    - name: Copy talend-remote-engine.service
      become: yes
      ansible.builtin.copy:
        src: /home/azureuser/Talend-RemoteEngine-V2.11.7/bin/talend-remote-engine.service
        dest: /etc/systemd/system/
        remote_src: true 
    - name: Start Talend Remote Engine service
      ansible.builtin.service:
        name: talend-remote-engine.service
        state: started
        enabled: yes