 - name: Install Remote Engine Playbook
   gather_facts: true
   hosts: all
   become: true

   vars: 
     ansible_user: azureuser 

   tasks:
    
    - name: Install OpenJDK11
      become: yes
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache : true 
    
    - name: Install unzip 
      ansible.builtin.apt:
        name: unzip
        state: present 
    
    - name: Download Talend Remote Engine 
      become: yes
      ansible.builtin.copy:
        src: '/root/Talend-RemoteEngine-V{{ tre_version }}.zip'
        dest: '/home/{{ ansible_user }}/'
    
    - name: Extract Talend Remote Engine file
      ansible.builtin.unarchive:
        src: '/home/{{ ansible_user }}/Talend-RemoteEngine-V{{ tre_version }}.zip'
        dest: '/home/{{ ansible_user }}/'
        remote_src: true 
    
    - name: customize /etc/environment
      become: true 
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        line: "JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64"

    - name: Prepare environment
      become: true
      ansible.builtin.shell: |
        export PAIRING_KEY=$(cat preAuthoKey.txt)
        echo "remote.engine.pre.authorized.key = $PAIRING_KEY" > 'Talend-RemoteEngine-V{{ tre_version }}/etc/preauthorized.key.cfg'
        echo "pairing.service.url=https://pair.eu.cloud.talend.com" > 'Talend-RemoteEngine-V{{ tre_version }}/etc/org.talend.ipaas.rt.pairing.client.cfg'
    
    - name: Install Remote Engine
      become: true
      ansible.builtin.shell: |
        cd '/home/{{ ansible_user }}/Talend-RemoteEngine-V{{ tre_version }}/bin'
        (echo feature:install wrapper; echo wrapper:install -n talend-remote-engine; echo logout) | sh trun 
      environment: 
        JAVA_HOME: /usr/lib/jvm/java-1.11.0-openjdk-amd64
    - name: Copy talend-remote-engine.service
      become: yes
      ansible.builtin.copy:
        src: '/home/{{ ansible_user }}/Talend-RemoteEngine-V{{ tre_version }}/bin/talend-remote-engine.service'
        dest: /etc/systemd/system/
        remote_src: true 
    - name: Start Talend Remote Engine service
      ansible.builtin.service:
        name: talend-remote-engine.service
        state: started
        enabled: yes